main: Puerto.o Arribo.o Barco.o BarcoPasajeros.o BarcoPequero.o DtPuerto.o DtArribo.o DtBarco.o DtBarcoPasajeros.o DtBarcoPesquero.o DtFecha.o main.o
  g++ Puerto.o Arribo.o Barco.o BarcoPasajeros.o BarcoPequero.o DtPuerto.o DtArribo.o DtBarco.o DtBarcoPasajeros.o DtBarcoPesquero.o DtFecha.o main.o -o sistema


Puerto.o: Puerto.cpp

Arribo.o: Arribo.cpp

Barco.o: Barco.cpp
	
BarcoPasajeros.o: BarcoPasajeros.cpp

BarcoPequero.o: BarcoPequero.cpp

DtPuerto.o: DtPuerto.cpp

DtArribo.o: DtArribo.cpp

DtBarco.o: DtBarco.cpp

DtBarcoPasajeros.o: DtBarcoPasajeros.cpp

DtBarcoPesquero.o: DtBarcoPesquero.cpp

DtFecha.o: DtFecha.cpp

main.o: main.cpp

clean:
	rm -rf *.o sistema
	clear